//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.16.0.5
//     Timestamp      : 19/07/2023 12:35:44
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE TelloFakeGUI

    PUBLIC PARTIAL CLASS MainWindow

        /// <summary>
        /// Required designer variable.
        /// </summary>
        private components	:=	NULL AS System.ComponentModel.IContainer
		PRIVATE textMessages AS System.Windows.Forms.TextBox
		PRIVATE panel1 AS System.Windows.Forms.Panel
		PRIVATE labelInfo AS System.Windows.Forms.Label
		PRIVATE buttonStop AS System.Windows.Forms.Button
		PRIVATE panel2 AS System.Windows.Forms.Panel
		PRIVATE pictureAlt AS System.Windows.Forms.PictureBox
		PRIVATE statusStrip1 AS System.Windows.Forms.StatusStrip
		PRIVATE statusLabel AS System.Windows.Forms.ToolStripStatusLabel
		PRIVATE panelCommand AS System.Windows.Forms.Panel
		PRIVATE buttonStart AS System.Windows.Forms.Button

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override method Dispose(disposing as logic) as void strict

            if (disposing .and. (components != null))
                components:Dispose()
            endif
            Super:Dispose(disposing)
			return
        end method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private METHOD InitializeComponent() AS VOID STRICT
			SELF:textMessages	:=	System.Windows.Forms.TextBox{}
			SELF:panel1	:=	System.Windows.Forms.Panel{}
			SELF:labelInfo	:=	System.Windows.Forms.Label{}
			SELF:buttonStop	:=	System.Windows.Forms.Button{}
			SELF:panel2	:=	System.Windows.Forms.Panel{}
			SELF:pictureAlt	:=	System.Windows.Forms.PictureBox{}
			SELF:statusStrip1	:=	System.Windows.Forms.StatusStrip{}
			SELF:statusLabel	:=	System.Windows.Forms.ToolStripStatusLabel{}
			SELF:panelCommand	:=	System.Windows.Forms.Panel{}
			SELF:buttonStart	:=	System.Windows.Forms.Button{}
			SELF:panel1:SuspendLayout()
			SELF:panel2:SuspendLayout()
			((System.ComponentModel.ISupportInitialize)(SELF:pictureAlt)):BeginInit()
			SELF:statusStrip1:SuspendLayout()
			SELF:panelCommand:SuspendLayout()
			SELF:SuspendLayout()
			//	
			//	textMessages
			//	
			SELF:textMessages:Location	:=	System.Drawing.Point{16, 20}
			SELF:textMessages:Multiline	:=	true
			SELF:textMessages:Name	:=	"textMessages"
			SELF:textMessages:ReadOnly	:=	true
			SELF:textMessages:ScrollBars	:=	System.Windows.Forms.ScrollBars.Vertical
			SELF:textMessages:Size	:=	System.Drawing.Size{276, 346}
			SELF:textMessages:TabIndex	:=	0
			//	
			//	panel1
			//	
			SELF:panel1:Controls:Add(SELF:labelInfo)
			SELF:panel1:Location	:=	System.Drawing.Point{12, 48}
			SELF:panel1:Name	:=	"panel1"
			SELF:panel1:Size	:=	System.Drawing.Size{200, 384}
			SELF:panel1:TabIndex	:=	7
			//	
			//	labelInfo
			//	
			SELF:labelInfo:AutoSize	:=	true
			SELF:labelInfo:Location	:=	System.Drawing.Point{16, 20}
			SELF:labelInfo:Name	:=	"labelInfo"
			SELF:labelInfo:Size	:=	System.Drawing.Size{0, 16}
			SELF:labelInfo:TabIndex	:=	5
			//	
			//	buttonStop
			//	
			SELF:buttonStop:Location	:=	System.Drawing.Point{621, 6}
			SELF:buttonStop:Name	:=	"buttonStop"
			SELF:buttonStop:Size	:=	System.Drawing.Size{75, 30}
			SELF:buttonStop:TabIndex	:=	6
			SELF:buttonStop:Text	:=	"Stop"
			SELF:buttonStop:UseVisualStyleBackColor	:=	true
			SELF:buttonStop:Visible	:=	false
			SELF:buttonStop:Click	+=	System.EventHandler{ SELF, @buttonStop_Click() }
			//	
			//	panel2
			//	
			SELF:panel2:Controls:Add(SELF:pictureAlt)
			SELF:panel2:Location	:=	System.Drawing.Point{231, 48}
			SELF:panel2:Name	:=	"panel2"
			SELF:panel2:Size	:=	System.Drawing.Size{139, 384}
			SELF:panel2:TabIndex	:=	8
			//	
			//	pictureAlt
			//	
			SELF:pictureAlt:Image	:=	global::TelloFakeGUI.Properties.Resources.telloUp
			SELF:pictureAlt:Location	:=	System.Drawing.Point{23, 278}
			SELF:pictureAlt:Name	:=	"pictureAlt"
			SELF:pictureAlt:Size	:=	System.Drawing.Size{100, 100}
			SELF:pictureAlt:SizeMode	:=	System.Windows.Forms.PictureBoxSizeMode.StretchImage
			SELF:pictureAlt:TabIndex	:=	0
			SELF:pictureAlt:TabStop	:=	false
			//	
			//	statusStrip1
			//	
			SELF:statusStrip1:ImageScalingSize	:=	System.Drawing.Size{20, 20}
			SELF:statusStrip1:Items:AddRange(<System.Windows.Forms.ToolStripItem>{ SELF:statusLabel })
			SELF:statusStrip1:Location	:=	System.Drawing.Point{0, 455}
			SELF:statusStrip1:Name	:=	"statusStrip1"
			SELF:statusStrip1:Size	:=	System.Drawing.Size{715, 22}
			SELF:statusStrip1:TabIndex	:=	10
			SELF:statusStrip1:Text	:=	"statusStrip1"
			//	
			//	statusLabel
			//	
			SELF:statusLabel:Name	:=	"statusLabel"
			SELF:statusLabel:Size	:=	System.Drawing.Size{0, 16}
			//	
			//	panelCommand
			//	
			SELF:panelCommand:Controls:Add(SELF:textMessages)
			SELF:panelCommand:Location	:=	System.Drawing.Point{386, 48}
			SELF:panelCommand:Name	:=	"panelCommand"
			SELF:panelCommand:Size	:=	System.Drawing.Size{310, 384}
			SELF:panelCommand:TabIndex	:=	9
			//	
			//	buttonStart
			//	
			SELF:buttonStart:Location	:=	System.Drawing.Point{621, 6}
			SELF:buttonStart:Name	:=	"buttonStart"
			SELF:buttonStart:Size	:=	System.Drawing.Size{75, 30}
			SELF:buttonStart:TabIndex	:=	5
			SELF:buttonStart:Text	:=	"Start"
			SELF:buttonStart:UseVisualStyleBackColor	:=	true
			SELF:buttonStart:Click	+=	System.EventHandler{ SELF, @buttonStart_Click() }
			//	
			//	MainWindow
			//	
			SELF:AutoScaleDimensions	:=	System.Drawing.SizeF{8, 16}
			SELF:AutoScaleMode	:=	System.Windows.Forms.AutoScaleMode.Font
			SELF:ClientSize	:=	System.Drawing.Size{715, 477}
			SELF:Controls:Add(SELF:panel1)
			SELF:Controls:Add(SELF:buttonStop)
			SELF:Controls:Add(SELF:panel2)
			SELF:Controls:Add(SELF:statusStrip1)
			SELF:Controls:Add(SELF:panelCommand)
			SELF:Controls:Add(SELF:buttonStart)
			SELF:MaximizeBox	:=	false
			SELF:MinimizeBox	:=	false
			SELF:Name	:=	"MainWindow"
			SELF:Text	:=	"Tello Fake"
			SELF:panel1:ResumeLayout(false)
			SELF:panel1:PerformLayout()
			SELF:panel2:ResumeLayout(false)
			((System.ComponentModel.ISupportInitialize)(SELF:pictureAlt)):EndInit()
			SELF:statusStrip1:ResumeLayout(false)
			SELF:statusStrip1:PerformLayout()
			SELF:panelCommand:ResumeLayout(false)
			SELF:panelCommand:PerformLayout()
			SELF:ResumeLayout(false)
			SELF:PerformLayout()
		END METHOD
        #endregion
    END CLASS 
END NAMESPACE
